### ISSUE TITLE
makeqsotemplate() for weaker quasars

### ISSUE THREAD

**Issue by cbertemes** [Q3D/q3dfit#12]
Minor point:
cube.makeqsotemplate() could use "cols" & "rows" arguments to specify which spaxel should be used for the template. 
By default it is the brightest one. 
But in some cubes with moderate-luminosity quasars, technical artifacts can make edge spaxels seem artificially bright, and the procedure then may use an edge spaxel as a template.

**Comment by drupke** [comment]
Implemented this.
