### ISSUE TITLE
Error fitting spaxels with q3dfit v1.1.1

### ISSUE THREAD

**Issue by swethasnkr** [Q3D/q3dfit#14]
I'm running into the following issue when fitting spaxels with q3dfit v1.1.1: 

File ~/opt/anaconda2/envs/q3dfit-f2m1106/lib/python3.8/site-packages/q3dfit/fitspec.py:629, in fitspec(wlambda, flux, err, dq, zstar, listlines, listlinesz, ncomp, specConv, q3di, maskwidths, peakinit, quiet, siginit_gas, siginit_stars, siglim_gas, tweakcntfit, logfile)
    625             q3do.perror_errspec[fluxlab] = \
    626                 np.median(gderr[ipklo:ipkhi+1])
    627             # Deal with flux pegging at boundary and no error
    628             # from lmfit
--> 629             if np.isnan(q3do.perror[fluxlab]):
    630                 q3do.perror[fluxlab] = q3do.perror_errspec[fluxlab]
    632 # Flux peak errors from fit residual.
    633 # resid = gdflux - continuum - specfit
    634 # q3do.perror_resid = copy.deepcopy(q3do.perror)
   (...)
    662 #             perror_resid[ifluxpk[i]] = \
    663 #                 np.sqrt(np.mean(np.power(resid[wlo:whi], 2.)))

**TypeError: ufunc 'isnan' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''**

I have tried fitting a couple different spaxels, and receive the same error.

**Comment by drupke** [comment]
Swetha, Hadley found the same error and came up with a fix. I’ll push a fix shortly.

David S. N. Rupke, Ph.D. (he/him)
Associate Professor of Physics
Rhodes College
901-402-1797
https://rhodes.zoom.us/my/drupke <https://rhodes.zoom.us/my/drupke>

**Comment by drupke** [comment]
@swethasnkr, I just pushed the hotfix. Lemme know if it doesn't work. I'm not sure where the problem came in, as the test notebooks all ran fine, but there you go.

**Comment by swethasnkr** [comment]
Hi Dave,Thank you! I’ll keep you posted. Best,SwethaOn Apr 10, 2023, at 5:46 PM, David Rupke ***@***.***> wrote:﻿
@swethasnkr, I just pushed the hotfix. Lemme know if it doesn't work. I'm not sure where the problem came in, as the test notebooks all ran fine, but there you go.
