### ISSUE TITLE
np.float error.

### ISSUE THREAD

**Issue by gabrieloliveira2428** [Q3D/q3dfit#16]
https://github.com/Q3D/q3dfit/blob/b0042690a1c363e30d965a6c089735ab210e7097/q3dfit/readcube.py#L492

This line raises an error when running q3dfit. Switching to the np.float32() function solves the issue.

**Comment by drupke** [comment]
@gabrieloliveira2428 , thanks for catching this! I've fixed it and will include it in the next patch release.
