### ISSUE TITLE
Specifying different amount of components for different lines

### ISSUE THREAD

**Issue by kykyelric** [Q3D/q3dfit#24]
Just like how you can specify different siginit or zinit by assigning an array as the values of a dictionary, e.g.
`
siginit_gas['H2_00_S3'] = np.full((ncols,nrows,maxncomp), 100)`  where `siginit_gas` is a dictionary with various lines as key values,

can `q3di.maxncomp` be specified as different values for the lines in a fit?

**Comment by drupke** [comment]
You can set q3di.ncomp for different lines; maxncomp is a constant max just to give the array some fixed dimensionality, and shouldn't need to vary among lines.
