### ISSUE TITLE
Import error in psf_sub.py prevents convolution

### ISSUE THREAD

**Issue by cbertemes** [Q3D/q3dfit#7]
Currently psf_sub.py crashes on "from q3dfit.cube_convolve import convolve_cube", because cube_convolve.py doesn't exist anymore, and as a result, the later call to convolve_cube() does not work. 
Did this routine move to readcube? Thanks!

**Comment by drupke** [comment]
Caroline, that's correct. The `cube` class now has a `convolve` method attached to it. It can also write the convolved cube back to a file with `writefits`. If you're trying to use psf_sub.py, just substitute the new method, push the changes, and then close the issue.

**Comment by drupke** [comment]
Closing stale issue.
